apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-minikube

  
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-ns
  namespace: jenkins-minikube
spec:
  hard:
    configmaps: '5'
    cpu: '4'
    memory: 2Gi
    pods: '2'
    replicationcontrollers: '3'
    secrets: '5'
    services: '5'
    services.loadbalancers: '5'

---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range-ns
  namespace: jenkins-minikube
spec:
  limits:
  - default:
      cpu: '0.2'
      memory: 128Mi
    defaultRequest:
      cpu: '0.2'
      memory: 128Mi
    type: Container
