apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-minikube

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-ns
  namespace: jenkins-minikube
spec:
  hard:
    configmaps: '5'
    cpu: '4'
    memory: 6Gi
    pods: '2'
    replicationcontrollers: '3'
    secrets: '50'
    services: '5'
    services.loadbalancers: '5'

---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range-ns
  namespace: jenkins-minikube
spec:
  limits:
  - default:
      cpu: '0.2'
      memory: 128Mi
    defaultRequest:
      cpu: '0.2'
      memory: 128Mi
    type: Container

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ruby-web-application-network-policy
spec:
  podSelector:
    matchLabels:
      service_name: ruby-web-application
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - ipBlock:
          cidr: "0.0.0.0/0"
  egress:
    - {}