apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.service_name }}-ingress
  annotations:
    kubernets.io/ingress.class: "nginx"
spec:
  defaultBackend:
    service:
      name: {{ .Values.service_name }}
      port:
        number: 80
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.service_name }}
                port:
                  number: 80